### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by scribblemaniac** [scribblemaniac/MCEdit2Blender#1]
Our primary focus for v1.0 is to get vanilla blocks rendering the same as they do in vanilla minecraft. Here is a list of features that still need to be implemented before v1.0 can be released, in no particular order:
- [ ] Mob spawner (no entity inside)
- [ ] Heads
- [ ] Chests
- [ ] Rails
- [ ] Redstone wire (and various related blocks)
- [ ] Water
- [ ] Lava
- [ ] Glass pane
- [ ] Iron bars
- [ ] Various plants
- [ ] Fences
- [ ] Cobblestone wall
- [ ] Fence gates
- [ ] Vines
- [ ] Beacons (with beam)
- [ ] Pressure plates
- [ ] Buttons
- [ ] Levers
- [ ] Doors
- [ ] Trapdoors
- [ ] Huge mushroom blocks (fix textures)
- [ ] Torches
- [ ] Cake
- [ ] Tripwire
- [ ] Tripwire hook
- [ ] Cocoa
- [ ] Fire (sides)
- [ ] Lily pad
- [ ] Enchantment table (book closed only and rotatable)
- [ ] Signs
- [ ] Brewing stand (no potions)
- [ ] Leaves (fancy)
- [ ] Tall grass
- [ ] Furnaces
- [ ] Flower pots
- [ ] Pistons
- [ ] Anvils
- [ ] Clouds
- [ ] Sky coloring
- [ ] Setting material viewport color
- [ ] Basic biome support (for grass, tall grass, and leaves, no blending)
- [ ] Sample renders, publicity (this should only be done when nearing completion of v1.0)

A few things that will not be in the v1.0 release, but are planned for a later date:
- Mod support
- Texture pack support
- Particles
- Blender internal support
- Options for greater user control
- Working redstone wire

This list is subject to change if necessary.
